/**
 * Cache-key ⇔ content coherence guard (the #92 seam mechanism).
 *
 * A whole class of caches key a compiled artifact (WGSL / a kernel spec) under
 * a CHEAP structural key computed WITHOUT running the codegen — the point of
 * the key is to skip codegen on a hit. That is a `key ≠ content` seam: the key
 * builder and the content builder must stay in lockstep BY HAND. Any field the
 * codegen bakes in but the key omits (a stride, an offset, a dtype, a shape a
 * fused recipe reads) makes two genuinely-different artifacts collide on ONE
 * cache entry — a stale pipeline is served deterministically and SILENTLY.
 * #91 killed the members where the key could simply BE the content
 * (`getPipeline(ctx, wgsl, wgsl)`); this guards the members that keep `key ≠
 * content` by design (fusion pipeline cache, row-program kernel cache).
 *
 * The mechanism (generalized from tile-dispatch's bespoke `getConfigBuffer`
 * byte-compare): on a cache HIT, under strict mode or a cheap sampled fraction,
 * REGENERATE the content and assert it equals what was cached under this key.
 * A mismatch means the key under-spans the codegen → LOUD error, never silent
 * staleness. On a MISS the content is generated anyway, so there is nothing to
 * check (and no cost); the guard only ever fires on hits.
 *
 * No new env flag: always-on checking is gated under the existing
 * `TORCHLETTE_STRICT_GPU` strict machinery (vitest enables it via env in the
 * test project), and OUTSIDE strict mode a cheap deterministic 1/N sampling
 * keeps a residual always-on tripwire in production runs at negligible cost
 * (the first hit on every key is always checked, so an under-spanning key is
 * caught on its second collision regardless of sampling).
 */

import { ENV } from "../../core/env";

const STRICT = ENV.TORCHLETTE_STRICT_GPU === "1";

// Outside strict mode, sample 1-in-SAMPLE_RATE hits per key. The first hit on a
// key is ALWAYS checked (a fresh key starts its counter at 0 → 0 % N === 0), so
// a colliding under-spanned key is caught the first time it is re-requested; the
// sampling only thins the cost of re-checking a key that has already proven
// coherent many times.
const SAMPLE_RATE = 64;

/** Per-guard-site state: how many times each key has been hit (for sampling). */
interface GuardState {
  hits: Map<string, number>;
}

/**
 * Create a guard bound to one cache site. `label` names the site in errors;
 * `content` is the cached artifact type; `equal` compares two artifacts (string
 * === for WGSL; a field compare for a spec).
 *
 * Call `check(key, cached, regenerate)` on every cache HIT. It decides — via
 * strict mode / sampling — whether to run `regenerate()` and assert the result
 * equals `cached`. On mismatch it throws (the coherence contract is broken; a
 * silently-served stale artifact would corrupt results with no crash — the
 * worst failure mode). On a match, or when not sampled, it is a cheap no-op.
 */
export function makeCacheKeyGuard<TContent>(
  label: string,
  equal: (a: TContent, b: TContent) => boolean,
  describe: (a: TContent, b: TContent) => string,
): {
  check: (key: string, cached: TContent, regenerate: () => TContent) => void;
  state: GuardState;
} {
  const state: GuardState = { hits: new Map() };

  function check(
    key: string,
    cached: TContent,
    regenerate: () => TContent,
  ): void {
    const n = state.hits.get(key) ?? 0;
    state.hits.set(key, n + 1);
    // Strict: check every hit. Otherwise: check the first hit on a key and
    // every SAMPLE_RATE-th thereafter.
    const sampled = STRICT || n % SAMPLE_RATE === 0;
    if (!sampled) return;

    const fresh = regenerate();
    if (!equal(cached, fresh)) {
      throw new Error(
        `cache-key incoherence at '${label}': the cache key under-spans the ` +
          `codegen — two different artifacts collided on key '${key}'. The ` +
          `structural key omits a field the content builder reads, so a stale ` +
          `artifact would be served silently (single-source-at-seams / #91-#92 ` +
          `class). ${describe(cached, fresh)}`,
      );
    }
  }

  return { check, state };
}

/**
 * WGSL generated by the tile-IR codegen is only ever ALPHA-equivalent across
 * two invocations, never byte-identical: local bindings are named from values
 * that vary run-to-run WITHOUT changing kernel semantics —
 *   - `t<node.id>`  (fusion node locals; the id is the graph node, which
 *      differs between two step-graphs that CSE to the same structural key),
 *   - `_<hint><n>`  (freshVar: `_cse7`, `_flat12`, … — a session-monotonic
 *      counter reset only at teardown).
 * A byte comparison would flag every legitimate cache hit as "incoherent"
 * (measured: it fired on ordinary training and forced the fusion path to fall
 * back to sequential — a real regression, and it would MASK true underspans).
 * So the guard compares WGSL up to renaming of these generated identifiers.
 *
 * `normalizeWgsl` rewrites each generated identifier to a placeholder assigned
 * in first-appearance order (a consistent renaming = alpha-equivalence). Two
 * kernels that differ ONLY in generated names normalize to the same string; a
 * kernel that differs in STRUCTURE (a dropped stride, a different op, a swapped
 * operand — the actual underspan class) still differs after normalization and
 * trips the guard.
 */
const GENERATED_IDENT = /\b(?:t\d+|_[A-Za-z]+\d+)\b/g;

export function normalizeWgsl(wgsl: string): string {
  const mapping = new Map<string, string>();
  return wgsl.replace(GENERATED_IDENT, (name) => {
    let canon = mapping.get(name);
    if (canon === undefined) {
      canon = `«${mapping.size}»`; // order-of-first-appearance placeholder
      mapping.set(name, canon);
    }
    return canon;
  });
}

/** Alpha-equivalence: equal WGSL up to renaming of generated identifiers. */
export function wgslContentEqual(a: string, b: string): boolean {
  return a === b || normalizeWgsl(a) === normalizeWgsl(b);
}

/** A short diff description for a (normalized) WGSL mismatch. */
export function describeWgslMismatch(cached: string, fresh: string): string {
  const a = normalizeWgsl(cached);
  const b = normalizeWgsl(fresh);
  if (a.length !== b.length) {
    return `normalized content is ${a.length} vs ${b.length} chars (structural difference, not just renaming).`;
  }
  let i = 0;
  while (i < a.length && a[i] === b[i]) i++;
  const ctx = 40;
  const from = Math.max(0, i - ctx);
  return (
    `first structural divergence at normalized char ${i}: ` +
    `cached …${JSON.stringify(a.slice(from, i + ctx))}… vs ` +
    `regenerated …${JSON.stringify(b.slice(from, i + ctx))}…`
  );
}
