/**
 * Tile-IR Reduction Kernel Factories
 *
 * Generates tile-IR kernel specs for all reduction operations:
 * sum (dim/full/chunked/preamble), max (dim/full), min, mean division.
 *
 * All reduction kernels are generated by a single unified factory
 * `makeReductionSpec()` parameterized on reduce op, dim/full,
 * preamble chain, and epilogue chain. Public exports are thin wrappers.
 *
 * Shapes are baked in as constants — the constant folding pass optimizes
 * aggressively (x*1→x, x/1→x, dead code elimination for rank-1 tensors).
 */

import type { DType } from "../types";
import { applyFusedOp, dtypeToTileIR } from "./fusion-tile-ir";
import { MAX_WORKGROUPS_PER_DIM, WORKGROUP_SIZE } from "./shape-utils";
import { compileTileKernel } from "./tile-compiler";
import {
  type BindingSpec,
  type BlockExpr,
  type DataType,
  elementwiseGrid,
  type KernelContext,
  singleWorkgroup,
  type TileKernelSpec,
} from "./tile-ir";

const WG = WORKGROUP_SIZE; // 256

// ============================================================================
// Types
// ============================================================================

export type ReduceOp = "sum" | "max" | "min";

/** Shape metadata for dimension-wise reduction. */
export interface DimInfo {
  inputShape: number[];
  inputStrides: number[];
  normalizedDims: number[];
  outShape: number[];
  outStrides: number[];
  inputToOutDim: number[];
  parallel: boolean;
}

/** Describes a single preamble chain op for kernel generation. */
export type PreambleChainKernelOp = {
  /** applyFusedOp-compatible op name (e.g., "mul", "cast_f32", "relu") */
  op: string;
  /** Number of inputs: 1 for unary, 2 for binary */
  arity: number;
  /** For non-first binary ops: which input position has the chain result (0 or 1) */
  chainInputPos?: 0 | 1;
};

/** Describes a single epilogue op to apply after a reduction. */
export type ReductionEpilogueOpDesc = {
  kind: string;
  toDtype?: DType;
  inputIndex?: number;
  op?: string;
};

/** Config for the unified reduction spec factory. */
export interface ReductionConfig {
  reduceOp: ReduceOp;
  /** undefined = full reduction (single scalar output). */
  dim?: DimInfo;
  /** Preamble: elementwise chain applied to loaded values before accumulation. */
  preamble?: {
    chainOps: PreambleChainKernelOp[];
    totalInputs: number;
    inputDtypes: DType[];
  };
  /** Epilogue: chain applied to the reduced result before storing. */
  epilogue?: {
    ops: ReductionEpilogueOpDesc[];
    outputDtype: DType;
  };
  /** Batch N independent same-shape reductions into one kernel (default: 1).
   *  When > 1, bindings are in0..inN-1 (read) + out0..outN-1 (read_write).
   *  Requires dim (no full reduction) and no preamble/epilogue. */
  count?: number;
}

// ============================================================================
// Index Computation
// ============================================================================

/**
 * Build a tile-IR expression that computes the linear input offset
 * from (outIdx, reduceIdx) using shape/stride metadata.
 *
 * All shape values are known at kernel-build time and become constants,
 * so the constant folder eliminates dead coordinates and trivial arithmetic.
 */
function buildInputOffset(
  ctx: KernelContext,
  outIdx: BlockExpr,
  reduceIdx: BlockExpr,
  dim: DimInfo,
): BlockExpr {
  const rank = dim.inputShape.length;

  // Decompose outIdx into output coordinates
  const outCoords =
    dim.outShape.length > 0 ? ctx.decomposeIndex(outIdx, dim.outShape) : [];

  // Decompose reduceIdx into reduction coordinates
  const reduceShape = dim.normalizedDims.map((d) => dim.inputShape[d]);
  const reduceCoords =
    reduceShape.length > 0 ? ctx.decomposeIndex(reduceIdx, reduceShape) : [];

  // Interleave output and reduction coordinates into input coordinates,
  // then linearize with input strides
  const inputCoords: BlockExpr[] = [];
  let reduceCoordIdx = 0;
  for (let d = 0; d < rank; d++) {
    if (dim.normalizedDims.includes(d)) {
      inputCoords.push(reduceCoords[reduceCoordIdx++]);
    } else {
      const outD = dim.inputToOutDim[d];
      if (outD >= 0 && outD < outCoords.length) {
        inputCoords.push(outCoords[outD]);
      } else {
        inputCoords.push(ctx.u32(0));
      }
    }
  }

  return ctx.linearizeIndex(inputCoords, dim.inputStrides);
}

// ============================================================================
// Preamble Chain Helper
// ============================================================================

/**
 * Apply a chain of preamble ops in-register within the reduction loop body.
 * External inputs are loaded from in0, in1, ... bindings at the given offset.
 *
 * First op: all inputs are external bindings.
 * Subsequent ops: chain result is one input, optional external is the other.
 */
function applyPreambleChain(
  ctx: KernelContext,
  chainOps: PreambleChainKernelOp[],
  offset: BlockExpr,
): BlockExpr {
  let externalIdx = 0;
  let result: BlockExpr;

  // First op: all inputs are external
  const firstInput = ctx.load(`in${externalIdx++}`, offset);
  if (chainOps[0].arity === 1) {
    result = applyFusedOp(ctx, chainOps[0].op, [firstInput]);
  } else {
    const secondInput = ctx.load(`in${externalIdx++}`, offset);
    result = applyFusedOp(ctx, chainOps[0].op, [firstInput, secondInput]);
  }

  // Remaining ops: chain result + optional external input
  for (let i = 1; i < chainOps.length; i++) {
    const op = chainOps[i];
    if (op.arity === 1) {
      result = applyFusedOp(ctx, op.op, [result]);
    } else {
      const ext = ctx.load(`in${externalIdx++}`, offset);
      if (op.chainInputPos === 1) {
        result = applyFusedOp(ctx, op.op, [ext, result]);
      } else {
        result = applyFusedOp(ctx, op.op, [result, ext]);
      }
    }
  }

  return result;
}

// ============================================================================
// Epilogue Chain Helper
// ============================================================================

/**
 * Apply a chain of epilogue ops to a reduced value in-register.
 * Binary ops load external inputs from ep_inN bindings at the output index.
 */
function applyEpilogueChain(
  ctx: KernelContext,
  value: BlockExpr,
  epilogueOps: ReductionEpilogueOpDesc[],
  outIdx: BlockExpr,
): BlockExpr {
  let result = value;
  for (const eop of epilogueOps) {
    if (eop.kind === "cast") {
      if (eop.toDtype === "f16") result = result.toF16();
      else if (eop.toDtype === "i32") result = result.toI32();
      else if (eop.toDtype === "u32") result = result.toU32();
      else result = result.toF32();
    } else if (
      eop.kind === "binary" &&
      eop.op &&
      eop.inputIndex !== undefined
    ) {
      const epInput = ctx.load(`ep_in${eop.inputIndex}`, outIdx);
      result = applyFusedOp(ctx, eop.op, [result, epInput]);
    } else if (eop.kind === "unary" && eop.op) {
      result = applyFusedOp(ctx, eop.op, [result]);
    }
  }
  return result;
}

/** Build epilogue bindings for external inputs. */
function buildEpilogueBindings(
  epilogueOps: ReductionEpilogueOpDesc[],
): Record<string, BindingSpec> {
  const bindings: Record<string, BindingSpec> = {};
  for (const eop of epilogueOps) {
    if (eop.kind === "binary" && eop.inputIndex !== undefined) {
      bindings[`ep_in${eop.inputIndex}`] = {
        storage: "read",
        type: "f32" as DataType,
      };
    }
  }
  return bindings;
}

// ============================================================================
// Unified Reduction Spec Factory
// ============================================================================

/**
 * Unified factory for all reduction kernel specs.
 *
 * Generates 3 kernel variants based on config:
 * - **Full reduction** (no dim): single workgroup, wgReduce → scalar output
 * - **Dim parallel** (dim.parallel=true): 1 workgroup per output element, wgReduce
 * - **Dim sequential** (dim.parallel=false): 1 thread per output element, loop
 *
 * All preamble/epilogue/reduce-op combinations compose cleanly.
 */
export function makeReductionSpec(config: ReductionConfig): TileKernelSpec {
  const { reduceOp, dim, preamble, epilogue, count = 1 } = config;
  const batched = count > 1;

  // --- Name ---
  const parts: string[] = [reduceOp];
  if (batched) parts.push(`batched${count}`);
  if (dim) {
    parts.push(dim.parallel ? "par" : "seq");
    parts.push(dim.inputShape.join("x"));
    parts.push(`d${dim.normalizedDims.join(",")}`);
  } else {
    parts.push("full");
  }
  if (preamble)
    parts.push("pre_" + preamble.chainOps.map((o) => o.op).join("+"));
  if (epilogue) parts.push("epi");
  const name = parts.join("_");

  // --- Bindings ---
  const bindings: Record<string, BindingSpec> = {};
  if (batched) {
    for (let i = 0; i < count; i++)
      bindings[`in${i}`] = { storage: "read", type: "f32" };
    for (let i = 0; i < count; i++)
      bindings[`out${i}`] = { storage: "read_write", type: "f32" };
  } else {
    if (preamble) {
      for (let i = 0; i < preamble.totalInputs; i++) {
        bindings[`in${i}`] = {
          storage: "read",
          type: (preamble.inputDtypes[i] || "f32") as DataType,
        };
      }
    } else {
      bindings.input = { storage: "read", type: "f32" };
    }
    if (epilogue) Object.assign(bindings, buildEpilogueBindings(epilogue.ops));
    const outType = epilogue ? dtypeToTileIR(epilogue.outputDtype) : "f32";
    bindings.out = { storage: "read_write", type: outType };
  }

  const needsF16 =
    preamble?.inputDtypes.some((d) => d === "f16") ||
    epilogue?.outputDtype === "f16" ||
    false;

  // --- Load function: bare load or preamble chain ---
  function emitLoad(ctx: KernelContext, offset: BlockExpr): BlockExpr {
    if (preamble) return applyPreambleChain(ctx, preamble.chainOps, offset);
    return ctx.load("input", offset);
  }

  // --- Finalize: apply optional epilogue ---
  function finalize(
    ctx: KernelContext,
    value: BlockExpr,
    outIdx: BlockExpr,
  ): BlockExpr {
    return epilogue
      ? applyEpilogueChain(ctx, value, epilogue.ops, outIdx)
      : value;
  }

  // ==========================================================================
  // Full reduction: single workgroup, wgReduce
  // ==========================================================================
  if (!dim) {
    return {
      name,
      workgroupSize: WG,
      bindings,
      enableF16: needsF16 || undefined,
      uniforms: { size: "u32" },
      grid: singleWorkgroup(),
      kernel(ctx) {
        const tid = ctx.localIndex();
        const result = ctx.wgReduce(
          reduceOp,
          tid,
          ctx.uniform("size"),
          WG,
          (i) => emitLoad(ctx, i),
        );
        const final = finalize(ctx, result, ctx.u32(0));
        ctx.guardedStore("out", tid.eq(ctx.u32(0)), ctx.u32(0), final);
      },
    };
  }

  // ==========================================================================
  // Dim parallel: 1 workgroup per output element, wgReduce
  // ==========================================================================
  if (dim.parallel) {
    return {
      name,
      workgroupSize: WG,
      bindings,
      enableF16: needsF16 || undefined,
      uniforms: { outSize: "u32", reductionSize: "u32" },
      grid: (u) => {
        const n = u.outSize;
        if (n <= MAX_WORKGROUPS_PER_DIM) return [n];
        return [
          Math.min(n, MAX_WORKGROUPS_PER_DIM),
          Math.ceil(n / MAX_WORKGROUPS_PER_DIM),
        ];
      },
      kernel(ctx) {
        const tid = ctx.localIndex();
        const outIdx = ctx.programId(0);
        ctx.ifThen(outIdx.ge(ctx.uniform("outSize")), () => ctx.emitReturn());

        const reductionSize = ctx.uniform("reductionSize");
        const result = ctx.wgReduce(reduceOp, tid, reductionSize, WG, (r) => {
          const off = buildInputOffset(ctx, outIdx, r, dim);
          return emitLoad(ctx, off);
        });

        const final = finalize(ctx, result, outIdx);
        ctx.guardedStore("out", tid.eq(ctx.u32(0)), outIdx, final);
      },
    };
  }

  // ==========================================================================
  // Dim sequential: 1 thread per output element, loop
  // ==========================================================================
  return {
    name,
    workgroupSize: WG,
    bindings,
    enableF16: needsF16 || undefined,
    uniforms: { outSize: "u32", reductionSize: "u32" },
    grid: elementwiseGrid(WG, { elementUniform: "outSize" }),
    kernel(ctx) {
      const idx = ctx.globalId(0);
      ctx.ifThen(idx.ge(ctx.uniform("outSize")), () => ctx.emitReturn());

      // Helpers that unify single/batched paths
      const load = (i: number, off: BlockExpr) =>
        batched ? ctx.load(`in${i}`, off) : emitLoad(ctx, off);
      const store = (i: number, val: BlockExpr) =>
        ctx.emitStore(
          batched ? `out${i}` : "out",
          idx,
          batched ? val : finalize(ctx, val, idx),
        );

      const reductionSize = ctx.uniform("reductionSize");

      if (reduceOp === "sum") {
        const accs = [];
        for (let i = 0; i < count; i++)
          accs.push(ctx.emitVar(`t${i}`, "f32", ctx.f32(0)));
        ctx.forRange(ctx.u32(0), reductionSize, (r) => {
          const off = buildInputOffset(ctx, idx, r, dim);
          for (let i = 0; i < count; i++) accs[i].addAssign(load(i, off));
        });
        for (let i = 0; i < count; i++) store(i, accs[i].get());
      } else {
        const firstOff = buildInputOffset(ctx, idx, ctx.u32(0), dim);
        const accs = [];
        for (let i = 0; i < count; i++)
          accs.push(ctx.emitVar(`a${i}`, "f32", load(i, firstOff)));
        ctx.forRange(ctx.u32(1), reductionSize, (r) => {
          const off = buildInputOffset(ctx, idx, r, dim);
          for (let i = 0; i < count; i++) {
            const val = load(i, off);
            accs[i].set(
              reduceOp === "max"
                ? accs[i].get().max(val)
                : accs[i].get().min(val),
            );
          }
        });
        for (let i = 0; i < count; i++) store(i, accs[i].get());
      }
    },
  };
}

// ============================================================================
// Helper: build DimInfo from positional args
// ============================================================================

export function dimInfo(
  inputShape: number[],
  inputStrides: number[],
  normalizedDims: number[],
  outShape: number[],
  outStrides: number[],
  inputToOutDim: number[],
  parallel: boolean,
): DimInfo {
  return {
    inputShape,
    inputStrides,
    normalizedDims,
    outShape,
    outStrides,
    inputToOutDim,
    parallel,
  };
}

// --- Mean division (elementwise, not a reduction) ---

export function makeMeanDivSpec(): TileKernelSpec {
  return {
    name: "meanDiv",
    workgroupSize: WG,
    bindings: {
      input: { storage: "read", type: "f32" },
      out: { storage: "read_write", type: "f32" },
    },
    uniforms: { size: "u32", count: "f32" },
    grid: elementwiseGrid(WG, { elementUniform: "size" }),
    kernel(ctx) {
      const idx = ctx.globalId(0);
      ctx.ifThen(idx.ge(ctx.uniform("size")), () => ctx.emitReturn());
      ctx.emitStore(
        "out",
        idx,
        ctx.load("input", idx).div(ctx.uniform("count")),
      );
    },
  };
}

// ============================================================================
// Chunked Sum Kernels (manual dispatch — return WGSL strings)
// ============================================================================

/**
 * Get compiled WGSL for the per-chunk sum kernel.
 * Each workgroup sums one chunk and writes to out[chunkIdx].
 *
 * We compile the WGSL via tile-IR but dispatch manually (the chunked path
 * needs buffer offset/size in bind group entries which tile-dispatch
 * doesn't support directly).
 */
export function getChunkedSumWGSL(): string {
  const spec: TileKernelSpec = {
    name: "sumChunk",
    workgroupSize: 1,
    bindings: {
      input: { storage: "read", type: "f32" },
      out: { storage: "read_write", type: "f32" },
    },
    uniforms: {
      chunkSize: "u32",
      chunkIdx: "u32",
    },
    grid: singleWorkgroup(),
    kernel(ctx) {
      const acc = ctx.emitVar("sum", "f32", ctx.f32(0));
      ctx.forRange(ctx.u32(0), ctx.uniform("chunkSize"), (i) => {
        acc.addAssign(ctx.load("input", i));
      });
      ctx.emitStore("out", ctx.uniform("chunkIdx"), acc.get());
    },
  };
  return compileTileKernel(spec);
}

/**
 * Get compiled WGSL for the final partials sum kernel (same as sumFull but workgroup_size(1)).
 */
export function getFinalSumWGSL(): string {
  const spec: TileKernelSpec = {
    name: "sumFinalPartials",
    workgroupSize: 1,
    bindings: {
      input: { storage: "read", type: "f32" },
      out: { storage: "read_write", type: "f32" },
    },
    uniforms: { size: "u32" },
    grid: singleWorkgroup(),
    kernel(ctx) {
      const acc = ctx.emitVar("sum", "f32", ctx.f32(0));
      ctx.forRange(ctx.u32(0), ctx.uniform("size"), (i) => {
        acc.addAssign(ctx.load("input", i));
      });
      ctx.emitStore("out", ctx.u32(0), acc.get());
    },
  };
  return compileTileKernel(spec);
}
