import { describe, expect, it } from "vitest";
import { applyMove, boundaryHash, makeMerge, makeSplit, withHash } from "./partition";
import type { Island } from "./types";

// Generated by the production implementation:
// pnpm exec tsx ../../tools/t-schedule-dump.ts --hash-vector
const VECTOR: Island[] = [
  { kind: "sequential", members: [0, 3, 4] },
  { kind: "fused", members: [7, 8, 11, 12] },
  { kind: "reduction", members: [19] },
];

describe("partition boundary hash", () => {
  it("matches the production TypeScript vector byte-for-byte", () => {
    expect(boundaryHash(VECTOR)).toBe(2962669663);
    expect(boundaryHash(VECTOR).toString(16)).toBe("b096c05f");
  });

  it("keeps merge and split structurally invertible", () => {
    const base = withHash([
      { kind: "fused", members: [1, 2] },
      { kind: "fused", members: [3, 4] },
    ]);
    const merged = makeMerge(base, 0, 1);
    expect(applyMove(applyMove(base, merged.forward), merged.inverse)).toEqual(base);

    const split = makeSplit(base, 0, 1);
    expect(applyMove(applyMove(base, split.forward), split.inverse)).toEqual(base);
  });
});
